const { Router } = require('express');
const { store } = require('../store');
const { ensureAuth } = require('../auth');
const router = Router();
const db = store('projects');
router.get('{/:id}', ensureAuth, (req, res) => { if (req.params.id) { const i = db.getById(req.params.id); return i ? res.json(i) : res.sendStatus(404); } res.json(db.getAll()); });
router.post('/', ensureAuth, (req, res) => { if (!req.body.name) return res.status(400).json({ error: 'name required' }); res.status(201).json(db.create({ ...req.body, owner: req.user.username })); });
router.put('/:id', ensureAuth, (req, res) => { const i = db.update(req.params.id, req.body); i ? res.json(i) : res.sendStatus(404); });
router.delete('/:id', ensureAuth, (req, res) => { db.remove(req.params.id) ? res.json({ ok: true }) : res.sendStatus(404); });
module.exports = router;
